### ISSUE TITLE
New version is failing on receiving keys...

### ISSUE THREAD

**Issue by plague-doctor** [tnt/ansible-gpg-keys-mod#8]
The task:

```
- name: "Download GPG keys..."
  gpg_import:
    state: "latest"
    key_id: "{{ item }}"
    tries: 2
    servers: "hkps.pool.sks-keyservers.net"
  with_items:
    - "0xEB559C7C54DDD393"
```

is failing. Module is throwing an exceptions:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):                                                                                                                  
  File "/tmp/ansible_awflY2/ansible_module_gpg_import.py", line 266, in <module>                                                                    
    main()                                                                                                                                          
  File "/tmp/ansible_awflY2/ansible_module_gpg_import.py", line 254, in main                                                                        
    gkm = GpgImport(module)                                                                                                                         
  File "/tmp/ansible_awflY2/ansible_module_gpg_import.py", line 120, in __init__                                                                    
    self._execute_task()                                                                                                                            
  File "/tmp/ansible_awflY2/ansible_module_gpg_import.py", line 144, in _execute_task                                                               
    res = self._repeat_command('refresh')                                                                                                           
  File "/tmp/ansible_awflY2/ansible_module_gpg_import.py", line 198, in _repeat_command                                                             
    raw_res = self.m.run_command(self.commands[cmd] % args)                                                                                         
TypeError: not all arguments converted during string formatting                                                                                     

failed: [localhost] (item=0xEB559C7C54DDD393) => {"failed": true, "invocation": {"module_name": "gpg_import"}, "item": "0xEB559C7C54DDD393", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_awflY2/ansible_module_gpg_import.py\", line 266, in <module>\n    main()\n  File \"/tmp/ansible_awflY2/ansible_module_gpg_import.py\", line 254, in main\n    gkm = GpgImport(module)\n  File \"/tmp/ansible_awflY2/ansible_module_gpg_import.py\", line 120, in __init__\n    self._execute_task()\n  File \"/tmp/ansible_awflY2/ansible_module_gpg_import.py\", line 144, in _execute_task\n    res = self._repeat_command('refresh')\n  File \"/tmp/ansible_awflY2/ansible_module_gpg_import.py\", line 198, in _repeat_command\n    raw_res = self.m.run_command(self.commands[cmd] % args)\nTypeError: not all arguments converted during string formatting\n", "module_stdout": "", "msg": "MODULE FAILURE"}              
```

The module is working fine when used the one from commit: ca4419e7ce58f028398d9ad2a452fb22b568a953

**Comment by tnt** [comment]
Sorry, I didn't review it and don't find time for it.

**Comment by joelnb** [comment]
I made a PR fixing this issue for anyone who is interested.

**Comment by marcstraube** [comment]
I have the same problem with the fixed version. Works perfect with ca4419e.

**Comment by joelnb** [comment]
Hi @marc-straube,

Does it work correctly for you if you apply the changes from https://github.com/tnt/ansible-gpg-import-module/pull/12? That PR has been open a while (and I also made https://github.com/tnt/ansible-gpg-import-module/pull/18 which does the same thing in a slightly different way) but not been merged. I think this is because, as he mentioned when merging my previous PR @tnt no longer uses this module and therefore doesn't have much time for it.

If that PR doesn't fix things for you any chance you could post the task where you are calling this module? And ideally post the output of the task when running the ansible with `-vvv`.
